---
site_name: fakeredis
site_author: Daniel Moran
site_description: >-
  Documentation for fakeredis python library
# Repository
repo_name: cunla/fakeredis
repo_url: https://github.com/cunla/fakeredis

# Copyright
copyright: Copyright &copy; 2022 - 2023 Daniel Moran

extra:
  generator: false
  analytics:
    provider: google
    property: G-GJBJBKXT19
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cunla
      repo: fakeredis
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true


nav:
  - Home: index.md
  - Redis stack: redis-stack.md
  - Commands documentation:
      - Redis commands:
          - Bitmap commands: redis-commands/Redis/BITMAP.md
          - Cluster commands: redis-commands/Redis/CLUSTER.md
          - Connection commands: redis-commands/Redis/CONNECTION.md
          - Generic commands: redis-commands/Redis/GENERIC.md
          - Geospatial indices commands: redis-commands/Redis/GEO.md
          - Bitmap commands: redis-commands/Redis/BITMAP.md
          - Hash commands: redis-commands/Redis/HASH.md
          - HyperLogLog commands: redis-commands/Redis/HYPERLOGLOG.md
          - List commands: redis-commands/Redis/LIST.md
          - Pub/Sub commands: redis-commands/Redis/PUBSUB.md
          - Scripting commands: redis-commands/Redis/SCRIPTING.md
          - Server commands: redis-commands/Redis/SERVER.md
          - Set commands: redis-commands/Redis/SET.md
          - Sorted Set commands: redis-commands/Redis/SORTEDSET.md
          - Stream commands: redis-commands/Redis/STREAM.md
          - String commands: redis-commands/Redis/STRING.md
          - Transactions commands: redis-commands/Redis/TRANSACTIONS.md
      - RedisJSON commands: redis-commands/RedisJSON/JSON
      - Search commands: redis-commands/RedisSearch/SEARCH
      - Suggestion commands: redis-commands/RedisSearch/SUGGESTION.md
      - Time Series commands: redis-commands/RedisTimeSeries/TIMESERIES.md
      - Probabilistic commands:
          - Bloom Filter commands: redis-commands/RedisBloom/BF.md
          - Cuckoo Filter commands: redis-commands/RedisBloom/CF.md
          - Count-Min Sketch commands: redis-commands/RedisBloom/CMS.md
          - t-digest commands: redis-commands/RedisBloom/TDIGEST.md
          - top-k commands: redis-commands/RedisBloom/TOPK.md
  - Guides:
      - Implementing support for a command: guides/implement-command.md
      - Write a new test case: guides/test-case.md
  - About:
      - Release Notes: about/changelog.md
      - Contributing: about/contributing.md
      - License: about/license.md

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs.sticky
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  highlightjs: true
  hljs_languages:
    - yaml
    - django
