name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: 'flake8 on code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache-dependency-path: poetry.lock
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: |
          python -m pip --quiet install poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          poetry install
      - name: Run flake8
        shell: bash
        run: |
          poetry run flake8 fakeredis/
      - name: Test import
        run: |
          poetry build
          pip install dist/fakeredis-*.tar.gz
          python -c 'import fakeredis'
  test:
    name: 'py:${{ matrix.python-version }},Redis:${{ matrix.redis-version }}, lupa:${{ matrix.lupa }}, cov:${{ matrix.coverage }}'
    needs: [ 'lint' ]
    runs-on: ubuntu-latest
    strategy:
      #      max-parallel: 5
      fail-fast: false
      matrix:
        redis-version: [ "6.2.7", "7.0.5" ]
        python-version: [ "3.7", "3.8", "3.10", '3.11' ]
        redis-py: [ '4.3.4' ]
        include:
          - python-version: "3.10" # should work fine with redis.asyncio
            redis-version: "6.2.7"
            redis-py: "4.3.4"
            lupa: "1.13"
          - python-version: "3.10" # should work fine with redis.asyncio
            redis-version: "7.0.5"
            redis-py: "4.3.4"
            lupa: "1.13"
            coverage: yes
    permissions:
      pull-requests: write
    services:
      redis:
        image: redis:${{ matrix.redis-version }}
        ports:
          - 6379:6379
    outputs:
      version: ${{ steps.getVersion.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache-dependency-path: poetry.lock
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        env:
          PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
        run: |
          python -m pip --quiet install poetry
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          poetry install
          poetry run pip install redis==${{ matrix.redis-py }}
      - name: Install lupa
        if: ${{ matrix.lupa }}
        run: |
          poetry run pip install lupa==${{ matrix.lupa }}
      - name: Get version
        id: getVersion
        shell: bash
        run: |
          VERSION=$(poetry version -s --no-ansi -n)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Test without coverage
        if: ${{ matrix.coverage != 'yes' }}
        run: |
          poetry run pytest -v
      - name: Test with coverage
        if: ${{ matrix.coverage == 'yes' }}
        uses: ./.github/actions/test-coverage
        with:
          github-secret: ${{ secrets.GITHUB_TOKEN }}
          gist-secret: ${{ secrets.GIST_SECRET }}
  # Prepare a draft release for GitHub Releases page for the manual verification
  # If accepted and published, release workflow would be triggered
  update_release_draft:
    permissions:
      # write permission is required to create a GitHub release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}